In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Training_set_begs.csv")

In [3]:
data.head()

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Treated_with_drugs,Patient_Age,Patient_Body_Mass_Index,Patient_Smoker,Patient_Rural_Urban,Patient_mental_condition,A,B,C,D,E,F,Z,Number_of_prev_cond,Survived_1_year
0,22374,8,3333,DX6,56,18.479385,YES,URBAN,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0
1,18164,5,5740,DX2,36,22.945566,YES,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
2,6283,23,10446,DX6,48,27.510027,YES,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,5339,51,12011,DX1,5,19.130976,NO,URBAN,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,33012,0,12513,NaN,128,1.348400,Cannot say,RURAL,Stable,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1

In [4]:
data.shape

(23097, 18)

In [5]:
data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')

In [6]:
data

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Treated_with_drugs,Patient_Age,Patient_Body_Mass_Index,Patient_Smoker,Patient_Rural_Urban,Patient_mental_condition,A,B,C,D,E,F,Z,Number_of_prev_cond,Survived_1_year
0,22374,8,3333,DX6,56,18.479385,YES,URBAN,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0
1,18164,5,5740,DX2,36,22.945566,YES,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
2,6283,23,10446,DX6,48,27.510027,YES,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,5339,51,12011,DX1,5,19.130976,NO,URBAN,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,33012,0,12513,NaN,128,1.348400,Cannot say,RURAL,Stable,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23092,15613,3,1548,DX2 DX4,14,18.643448,NO,RURAL,Stable,1.0,1.0,0.0,1.0,1.0,1.0,0.0,5.0,0
23093,15503,41,2769,DX6,55,23.684585,NO,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
23094,2167,24,7671,DX6,63,27.500039,YES,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
23095,31646,11,5764,DX3,25,23.719125,YES,RURAL,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1
23096,3947,21,6266,DX6,50,18.391156,YES,RURAL,Stable,1.0,0.0,1.0,1.0,1.0,0.0,0.0,4.0,0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23097 entries, 0 to 23096
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID_Patient_Care_Situation  23097 non-null  int64
 1   Diagnosed_Condition        23097 non-null  int64
 2   Patient_ID                 23097 non-null  int64
 3   Treated_with_drugs         23084 non-null  object
 4   Patient_Age                23097 non-null  int64
 5   Patient_Body_Mass_Index    23097 non-null  float64
 6   Patient_Smoker             23097 non-null  object
 7   Patient_Rural_Urban        23097 non-null  object
 8   Patient_mental_condition   23097 non-null  object
 9   A                          21862 non-null  float64
 10  B                          21862 non-null  float64
 11  C                          21862 non-null  float64
 12  D                          21862 non-null  float64
 13  E                          21862 non-null  float64
 14  F                          21862 non-null  float64
 15  Z                          21862 non-null  float64
 16  Number_of_prev_cond        21862 non-null  float64
 17  Survived_1_year            23097 non-null  int64
dtypes: float64(9), int64(5), object(4)
memory usage: 3.2+ MB

In [8]:
import seaborn as sns

In [11]:
data.Treated_with_drugs.mode()[0]

'DX6'

- Train-test split
- Missing Values
- Categorical variables
- EDA - Univariate and Bivariate
- Feature engineering
- Feature selection
- Model building
- Model evaluation

In [13]:
data.Treated_with_drugs.fillna(data.Treated_with_drugs.mode()[0],inplace=True)

In [15]:
data.A.fillna(data.A.mode()[0], inplace=True)

In [16]:
data.B.fillna(data.B.mode()[0], inplace=True)

In [17]:
data.C.fillna(data.C.mode()[0], inplace=True)

In [18]:
data.D.fillna(data.D.mode()[0], inplace=True)

In [19]:
data.E.fillna(data.E.mode()[0], inplace=True)

In [20]:
data.F.fillna(data.F.mode()[0], inplace=True)

In [21]:
data.Z.fillna(data.Z.mode()[0], inplace=True)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23097 entries, 0 to 23096
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID_Patient_Care_Situation  23097 non-null  int64
 1   Diagnosed_Condition        23097 non-null  int64
 2   Patient_ID                 23097 non-null  int64
 3   Treated_with_drugs         23097 non-null  object
 4   Patient_Age                23097 non-null  int64
 5   Patient_Body_Mass_Index    23097 non-null  float64
 6   Patient_Smoker             23097 non-null  object
 7   Patient_Rural_Urban        23097 non-null  object
 8   Patient_mental_condition   23097 non-null  object
 9   A                          23097 non-null  float64
 10  B                          23097 non-null  float64
 11  C                          23097 non-null  float64
 12  D                          23097 non-null  float64
 13  E                          23097 non-null  float64
 14  F                          23097 non-null  float64
 15  Z                          23097 non-null  float64
 16  Number_of_prev_cond        21862 non-null  float64
 17  Survived_1_year            23097 non-null  int64
dtypes: float64(9), int64(5), object(4)
memory usage: 3.2+ MB

In [26]:
data.Number_of_prev_cond.fillna(data.Number_of_prev_cond.median(),inplace=True)

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23097 entries, 0 to 23096
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID_Patient_Care_Situation  23097 non-null  int64
 1   Diagnosed_Condition        23097 non-null  int64
 2   Patient_ID                 23097 non-null  int64
 3   Treated_with_drugs         23097 non-null  object
 4   Patient_Age                23097 non-null  int64
 5   Patient_Body_Mass_Index    23097 non-null  float64
 6   Patient_Smoker             23097 non-null  object
 7   Patient_Rural_Urban        23097 non-null  object
 8   Patient_mental_condition   23097 non-null  object
 9   A                          23097 non-null  float64
 10  B                          23097 non-null  float64
 11  C                          23097 non-null  float64
 12  D                          23097 non-null  float64
 13  E                          23097 non-null  float64
 14  F                          23097 non-null  float64
 15  Z                          23097 non-null  float64
 16  Number_of_prev_cond        23097 non-null  float64
 17  Survived_1_year            23097 non-null  int64
dtypes: float64(9), int64(5), object(4)
memory usage: 3.2+ MB

In [29]:
data_enc=pd.get_dummies(data,columns=['Treated_with_drugs', 'Patient_Smoker', 'Patient_Rural_Urban','Patient_mental_condition'], drop_first=True)